### ISSUE TITLE
Image Generation Speed

### ISSUE THREAD

**Issue by themasterlink** [AIS-Bonn/stillleben#1]
How many different images can stillleben produce per second?

**Comment by xqms** [comment]
That highly depends on your requirements. The costly operation is physics simulation (i.e. scene generation), which can take up to 100ms depending on the scene complexity. However, you can render many different views from one object arrangement using random viewing poses. Additionally, if you properly pipeline the scene generation using multiple processes, you can easily achieve >100 fps on a single GPU. I think it could be pushed even further, but I never needed higher rates so far - CNN training is much slower ;)

The YCB example we provide is simplified as much as possible and does not use pipelining and multi-process computation. I'll add a more complicated example optimized for performance soon.

**Comment by themasterlink** [comment]
Thank you very much, that answers my question!
