### ISSUE TITLE
Question: How to get binary segmentation mask?

### ISSUE THREAD

**Issue by eendru** [AIS-Bonn/stillleben#7]
Could you provide an example for obtain binary segmentation mask from
```C++
 result = renderer.render(scene)
```

Thanks.

**Comment by xqms** [comment]
Hey, this is documented here: https://ais-bonn.github.io/stillleben/stillleben.RenderPassResult.html

If you just want to segment all objects against the background, you can use something like `result.class_index() != 0` to get a mask of all the pixels which do not contain background (background has class index 0).

**Comment by xqms** [comment]
I have to correct myself: use `result.instance_index() != 0`. The class index is not automatically set up, you have to set it using `mesh.class_index = N`.

**Comment by eendru** [comment]
Thank you!
